CREATE DATABASE Pizzaria;
GO

USE Pizzaria;


CREATE TABLE Sabor
( 

Id INT PRIMARY KEY IDENTITY (1,1),
Descricao VARCHAR(100) NOT NULL UNIQUE,
Valor SMALLMONEY NOT NULL,
DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())

);
CREATE TABLE Pedido
(
   Id INT PRIMARY KEY IDENTITY(1,1)
   SaborId INT NOT NULL,
   NomeCLiente VARCHAR(100) NULL,
   Total SMALLMONEY NOT NULL,
   DoisSabores BIT NOT NULL DEFAULT(0),
   DataPedido DATETIME NOT NULL,
   PedidoCancelado BIT NULL,
   DataCadastro DATETIME NOT NULL 

   CONSTRAINT fk_Pedido_Sabor FOREIGN KEY (SaborId) REFERENCES Sabor(Id)
);
